### ISSUE TITLE
Can you provide test data for ndt_2d/3d, please?

### ISSUE THREAD

**Issue by ruitingyuan** [cogsys-tuebingen/cslibs_ndt#3]
Can you provide test data for ndt_2d/3d, please?

**Comment by c-schulz** [comment]
Hello @ruitingyuan 

what kind of test data do you need? I think it should be possible to use the implementation with any kind of 2D/3D data. For an example, please take a look at [cslibs_mapping](https://github.com/cogsys-tuebingen/cslibs_mapping), there also is an exemplary launch file.

Best wishes

**Comment by c-schulz** [comment]
Hi @ruitingyuan,
in the `cslibs_mapping` repository, you can find a script to download exemplary data. There is also a new example launch file.
